cc_library(
    name = "engine",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    visibility = [
        "//entry:__pkg__",
    ],
    deps = [
        "//common",
        "//data",
        "//pricer",
    ],
)
