cc_library(
    name = "pricer",
    srcs = [],
    hdrs = [
        "base-pricer.h",
        "mock-pricer.h",
        "pricer.h",
    ],
    visibility = [
        "//engine:__pkg__",
    ],
    deps = [
        "//common",
        "@com_google_googletest//:gtest_main",
    ],
)
