cc_library(
    name = "data",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    visibility = [
        "//engine:__pkg__",
        "//entry:__pkg__",
    ],
    deps = [
        "//common",
        "//exchanges",
    ],
)
