on: [pull_request]

jobs:
  cpp_style_check:
    runs-on: ubuntu-latest
    name: Check C++ Style
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --recursive .
  
  unit_tests:
    runs-on: ubuntu-latest
    name: Build and run all tests
    steps:
    - uses: bazelbuild/setup-bazelisk@v2
    - uses: actions/checkout@v3
    - run: sudo apt install libboost-all-dev
    - run: sudo apt install libcurl4-gnutls-dev
    - run: sudo apt install libsqlite3-dev
    - run: wget https://github.com/CrowCpp/Crow/releases/download/v1.0%2B5/crow-v1.0+5.deb
    - run: sudo apt install ./crow-v1.0+5.deb

    - run: bazel build ...

    - run: bazel test --test_output=all ...
